//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityConfig) DeepCopyInto(out *AvailabilityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityConfig.
func (in *AvailabilityConfig) DeepCopy() *AvailabilityConfig {
	if in == nil {
		return nil
	}
	out := new(AvailabilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonSpec) DeepCopyInto(out *CommonSpec) {
	*out = *in
	in.EntityMetadata.DeepCopyInto(&out.EntityMetadata)
	if in.Device != nil {
		in, out := &in.Device, &out.Device
		*out = new(DeviceBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceRef != nil {
		in, out := &in.DeviceRef, &out.DeviceRef
		*out = new(DeviceRef)
		**out = **in
	}
	if in.Availability != nil {
		in, out := &in.Availability, &out.Availability
		*out = make([]AvailabilityConfig, len(*in))
		copy(*out, *in)
	}
	if in.Qos != nil {
		in, out := &in.Qos, &out.Qos
		*out = new(int)
		**out = **in
	}
	if in.Retain != nil {
		in, out := &in.Retain, &out.Retain
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonSpec.
func (in *CommonSpec) DeepCopy() *CommonSpec {
	if in == nil {
		return nil
	}
	out := new(CommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonStatus) DeepCopyInto(out *CommonStatus) {
	*out = *in
	if in.LastPublished != nil {
		in, out := &in.LastPublished, &out.LastPublished
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonStatus.
func (in *CommonStatus) DeepCopy() *CommonStatus {
	if in == nil {
		return nil
	}
	out := new(CommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceBlock) DeepCopyInto(out *DeviceBlock) {
	*out = *in
	if in.Identifiers != nil {
		in, out := &in.Identifiers, &out.Identifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceBlock.
func (in *DeviceBlock) DeepCopy() *DeviceBlock {
	if in == nil {
		return nil
	}
	out := new(DeviceBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceRef) DeepCopyInto(out *DeviceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceRef.
func (in *DeviceRef) DeepCopy() *DeviceRef {
	if in == nil {
		return nil
	}
	out := new(DeviceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityMetadata) DeepCopyInto(out *EntityMetadata) {
	*out = *in
	if in.EnabledByDefault != nil {
		in, out := &in.EnabledByDefault, &out.EnabledByDefault
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityMetadata.
func (in *EntityMetadata) DeepCopy() *EntityMetadata {
	if in == nil {
		return nil
	}
	out := new(EntityMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTAlarmControlPanel) DeepCopyInto(out *MQTTAlarmControlPanel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTAlarmControlPanel.
func (in *MQTTAlarmControlPanel) DeepCopy() *MQTTAlarmControlPanel {
	if in == nil {
		return nil
	}
	out := new(MQTTAlarmControlPanel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTAlarmControlPanel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTAlarmControlPanelList) DeepCopyInto(out *MQTTAlarmControlPanelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTAlarmControlPanel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTAlarmControlPanelList.
func (in *MQTTAlarmControlPanelList) DeepCopy() *MQTTAlarmControlPanelList {
	if in == nil {
		return nil
	}
	out := new(MQTTAlarmControlPanelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTAlarmControlPanelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTAlarmControlPanelSpec) DeepCopyInto(out *MQTTAlarmControlPanelSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.CodeArmRequired != nil {
		in, out := &in.CodeArmRequired, &out.CodeArmRequired
		*out = new(bool)
		**out = **in
	}
	if in.CodeDisarmRequired != nil {
		in, out := &in.CodeDisarmRequired, &out.CodeDisarmRequired
		*out = new(bool)
		**out = **in
	}
	if in.CodeTriggerRequired != nil {
		in, out := &in.CodeTriggerRequired, &out.CodeTriggerRequired
		*out = new(bool)
		**out = **in
	}
	if in.SupportedFeatures != nil {
		in, out := &in.SupportedFeatures, &out.SupportedFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTAlarmControlPanelSpec.
func (in *MQTTAlarmControlPanelSpec) DeepCopy() *MQTTAlarmControlPanelSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTAlarmControlPanelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTAlarmControlPanelStatus) DeepCopyInto(out *MQTTAlarmControlPanelStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTAlarmControlPanelStatus.
func (in *MQTTAlarmControlPanelStatus) DeepCopy() *MQTTAlarmControlPanelStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTAlarmControlPanelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTBinarySensor) DeepCopyInto(out *MQTTBinarySensor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTBinarySensor.
func (in *MQTTBinarySensor) DeepCopy() *MQTTBinarySensor {
	if in == nil {
		return nil
	}
	out := new(MQTTBinarySensor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTBinarySensor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTBinarySensorList) DeepCopyInto(out *MQTTBinarySensorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTBinarySensor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTBinarySensorList.
func (in *MQTTBinarySensorList) DeepCopy() *MQTTBinarySensorList {
	if in == nil {
		return nil
	}
	out := new(MQTTBinarySensorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTBinarySensorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTBinarySensorSpec) DeepCopyInto(out *MQTTBinarySensorSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.ExpireAfter != nil {
		in, out := &in.ExpireAfter, &out.ExpireAfter
		*out = new(int)
		**out = **in
	}
	if in.ForceUpdate != nil {
		in, out := &in.ForceUpdate, &out.ForceUpdate
		*out = new(bool)
		**out = **in
	}
	if in.OffDelay != nil {
		in, out := &in.OffDelay, &out.OffDelay
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTBinarySensorSpec.
func (in *MQTTBinarySensorSpec) DeepCopy() *MQTTBinarySensorSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTBinarySensorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTBinarySensorStatus) DeepCopyInto(out *MQTTBinarySensorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTBinarySensorStatus.
func (in *MQTTBinarySensorStatus) DeepCopy() *MQTTBinarySensorStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTBinarySensorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTButton) DeepCopyInto(out *MQTTButton) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTButton.
func (in *MQTTButton) DeepCopy() *MQTTButton {
	if in == nil {
		return nil
	}
	out := new(MQTTButton)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTButton) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTButtonList) DeepCopyInto(out *MQTTButtonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTButton, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTButtonList.
func (in *MQTTButtonList) DeepCopy() *MQTTButtonList {
	if in == nil {
		return nil
	}
	out := new(MQTTButtonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTButtonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTButtonSpec) DeepCopyInto(out *MQTTButtonSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTButtonSpec.
func (in *MQTTButtonSpec) DeepCopy() *MQTTButtonSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTButtonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTButtonStatus) DeepCopyInto(out *MQTTButtonStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTButtonStatus.
func (in *MQTTButtonStatus) DeepCopy() *MQTTButtonStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTButtonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTCamera) DeepCopyInto(out *MQTTCamera) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTCamera.
func (in *MQTTCamera) DeepCopy() *MQTTCamera {
	if in == nil {
		return nil
	}
	out := new(MQTTCamera)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTCamera) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTCameraList) DeepCopyInto(out *MQTTCameraList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTCamera, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTCameraList.
func (in *MQTTCameraList) DeepCopy() *MQTTCameraList {
	if in == nil {
		return nil
	}
	out := new(MQTTCameraList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTCameraList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTCameraSpec) DeepCopyInto(out *MQTTCameraSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTCameraSpec.
func (in *MQTTCameraSpec) DeepCopy() *MQTTCameraSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTCameraSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTCameraStatus) DeepCopyInto(out *MQTTCameraStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTCameraStatus.
func (in *MQTTCameraStatus) DeepCopy() *MQTTCameraStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTCameraStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClimate) DeepCopyInto(out *MQTTClimate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClimate.
func (in *MQTTClimate) DeepCopy() *MQTTClimate {
	if in == nil {
		return nil
	}
	out := new(MQTTClimate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTClimate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClimateList) DeepCopyInto(out *MQTTClimateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTClimate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClimateList.
func (in *MQTTClimateList) DeepCopy() *MQTTClimateList {
	if in == nil {
		return nil
	}
	out := new(MQTTClimateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTClimateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClimateSpec) DeepCopyInto(out *MQTTClimateSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.Modes != nil {
		in, out := &in.Modes, &out.Modes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FanModes != nil {
		in, out := &in.FanModes, &out.FanModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SwingModes != nil {
		in, out := &in.SwingModes, &out.SwingModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PresetModes != nil {
		in, out := &in.PresetModes, &out.PresetModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TempStep != nil {
		in, out := &in.TempStep, &out.TempStep
		*out = new(float64)
		**out = **in
	}
	if in.MinTemp != nil {
		in, out := &in.MinTemp, &out.MinTemp
		*out = new(float64)
		**out = **in
	}
	if in.MaxTemp != nil {
		in, out := &in.MaxTemp, &out.MaxTemp
		*out = new(float64)
		**out = **in
	}
	if in.Precision != nil {
		in, out := &in.Precision, &out.Precision
		*out = new(float64)
		**out = **in
	}
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClimateSpec.
func (in *MQTTClimateSpec) DeepCopy() *MQTTClimateSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTClimateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTClimateStatus) DeepCopyInto(out *MQTTClimateStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTClimateStatus.
func (in *MQTTClimateStatus) DeepCopy() *MQTTClimateStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTClimateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTCover) DeepCopyInto(out *MQTTCover) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTCover.
func (in *MQTTCover) DeepCopy() *MQTTCover {
	if in == nil {
		return nil
	}
	out := new(MQTTCover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTCover) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTCoverList) DeepCopyInto(out *MQTTCoverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTCover, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTCoverList.
func (in *MQTTCoverList) DeepCopy() *MQTTCoverList {
	if in == nil {
		return nil
	}
	out := new(MQTTCoverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTCoverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTCoverSpec) DeepCopyInto(out *MQTTCoverSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.PositionOpen != nil {
		in, out := &in.PositionOpen, &out.PositionOpen
		*out = new(int)
		**out = **in
	}
	if in.PositionClosed != nil {
		in, out := &in.PositionClosed, &out.PositionClosed
		*out = new(int)
		**out = **in
	}
	if in.TiltMin != nil {
		in, out := &in.TiltMin, &out.TiltMin
		*out = new(int)
		**out = **in
	}
	if in.TiltMax != nil {
		in, out := &in.TiltMax, &out.TiltMax
		*out = new(int)
		**out = **in
	}
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTCoverSpec.
func (in *MQTTCoverSpec) DeepCopy() *MQTTCoverSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTCoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTCoverStatus) DeepCopyInto(out *MQTTCoverStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTCoverStatus.
func (in *MQTTCoverStatus) DeepCopy() *MQTTCoverStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTCoverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDevice) DeepCopyInto(out *MQTTDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDevice.
func (in *MQTTDevice) DeepCopy() *MQTTDevice {
	if in == nil {
		return nil
	}
	out := new(MQTTDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceList) DeepCopyInto(out *MQTTDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceList.
func (in *MQTTDeviceList) DeepCopy() *MQTTDeviceList {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceSpec) DeepCopyInto(out *MQTTDeviceSpec) {
	*out = *in
	if in.Identifiers != nil {
		in, out := &in.Identifiers, &out.Identifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceSpec.
func (in *MQTTDeviceSpec) DeepCopy() *MQTTDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceStatus) DeepCopyInto(out *MQTTDeviceStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceStatus.
func (in *MQTTDeviceStatus) DeepCopy() *MQTTDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceTracker) DeepCopyInto(out *MQTTDeviceTracker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceTracker.
func (in *MQTTDeviceTracker) DeepCopy() *MQTTDeviceTracker {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceTracker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTDeviceTracker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceTrackerList) DeepCopyInto(out *MQTTDeviceTrackerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTDeviceTracker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceTrackerList.
func (in *MQTTDeviceTrackerList) DeepCopy() *MQTTDeviceTrackerList {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceTrackerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTDeviceTrackerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceTrackerSpec) DeepCopyInto(out *MQTTDeviceTrackerSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceTrackerSpec.
func (in *MQTTDeviceTrackerSpec) DeepCopy() *MQTTDeviceTrackerSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceTrackerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceTrackerStatus) DeepCopyInto(out *MQTTDeviceTrackerStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceTrackerStatus.
func (in *MQTTDeviceTrackerStatus) DeepCopy() *MQTTDeviceTrackerStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceTrackerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceTrigger) DeepCopyInto(out *MQTTDeviceTrigger) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceTrigger.
func (in *MQTTDeviceTrigger) DeepCopy() *MQTTDeviceTrigger {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTDeviceTrigger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceTriggerList) DeepCopyInto(out *MQTTDeviceTriggerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTDeviceTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceTriggerList.
func (in *MQTTDeviceTriggerList) DeepCopy() *MQTTDeviceTriggerList {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceTriggerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTDeviceTriggerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceTriggerSpec) DeepCopyInto(out *MQTTDeviceTriggerSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceTriggerSpec.
func (in *MQTTDeviceTriggerSpec) DeepCopy() *MQTTDeviceTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTDeviceTriggerStatus) DeepCopyInto(out *MQTTDeviceTriggerStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTDeviceTriggerStatus.
func (in *MQTTDeviceTriggerStatus) DeepCopy() *MQTTDeviceTriggerStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceTriggerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTEvent) DeepCopyInto(out *MQTTEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTEvent.
func (in *MQTTEvent) DeepCopy() *MQTTEvent {
	if in == nil {
		return nil
	}
	out := new(MQTTEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTEventList) DeepCopyInto(out *MQTTEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTEventList.
func (in *MQTTEventList) DeepCopy() *MQTTEventList {
	if in == nil {
		return nil
	}
	out := new(MQTTEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTEventSpec) DeepCopyInto(out *MQTTEventSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.EventTypes != nil {
		in, out := &in.EventTypes, &out.EventTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTEventSpec.
func (in *MQTTEventSpec) DeepCopy() *MQTTEventSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTEventStatus) DeepCopyInto(out *MQTTEventStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTEventStatus.
func (in *MQTTEventStatus) DeepCopy() *MQTTEventStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTEventStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTFan) DeepCopyInto(out *MQTTFan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTFan.
func (in *MQTTFan) DeepCopy() *MQTTFan {
	if in == nil {
		return nil
	}
	out := new(MQTTFan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTFan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTFanList) DeepCopyInto(out *MQTTFanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTFan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTFanList.
func (in *MQTTFanList) DeepCopy() *MQTTFanList {
	if in == nil {
		return nil
	}
	out := new(MQTTFanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTFanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTFanSpec) DeepCopyInto(out *MQTTFanSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.SpeedRangeMin != nil {
		in, out := &in.SpeedRangeMin, &out.SpeedRangeMin
		*out = new(int)
		**out = **in
	}
	if in.SpeedRangeMax != nil {
		in, out := &in.SpeedRangeMax, &out.SpeedRangeMax
		*out = new(int)
		**out = **in
	}
	if in.PresetModes != nil {
		in, out := &in.PresetModes, &out.PresetModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTFanSpec.
func (in *MQTTFanSpec) DeepCopy() *MQTTFanSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTFanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTFanStatus) DeepCopyInto(out *MQTTFanStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTFanStatus.
func (in *MQTTFanStatus) DeepCopy() *MQTTFanStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTFanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTHumidifier) DeepCopyInto(out *MQTTHumidifier) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTHumidifier.
func (in *MQTTHumidifier) DeepCopy() *MQTTHumidifier {
	if in == nil {
		return nil
	}
	out := new(MQTTHumidifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTHumidifier) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTHumidifierList) DeepCopyInto(out *MQTTHumidifierList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTHumidifier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTHumidifierList.
func (in *MQTTHumidifierList) DeepCopy() *MQTTHumidifierList {
	if in == nil {
		return nil
	}
	out := new(MQTTHumidifierList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTHumidifierList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTHumidifierSpec) DeepCopyInto(out *MQTTHumidifierSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.Modes != nil {
		in, out := &in.Modes, &out.Modes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinHumidity != nil {
		in, out := &in.MinHumidity, &out.MinHumidity
		*out = new(float64)
		**out = **in
	}
	if in.MaxHumidity != nil {
		in, out := &in.MaxHumidity, &out.MaxHumidity
		*out = new(float64)
		**out = **in
	}
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTHumidifierSpec.
func (in *MQTTHumidifierSpec) DeepCopy() *MQTTHumidifierSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTHumidifierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTHumidifierStatus) DeepCopyInto(out *MQTTHumidifierStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTHumidifierStatus.
func (in *MQTTHumidifierStatus) DeepCopy() *MQTTHumidifierStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTHumidifierStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTImage) DeepCopyInto(out *MQTTImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTImage.
func (in *MQTTImage) DeepCopy() *MQTTImage {
	if in == nil {
		return nil
	}
	out := new(MQTTImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTImageList) DeepCopyInto(out *MQTTImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTImageList.
func (in *MQTTImageList) DeepCopy() *MQTTImageList {
	if in == nil {
		return nil
	}
	out := new(MQTTImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTImageSpec) DeepCopyInto(out *MQTTImageSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTImageSpec.
func (in *MQTTImageSpec) DeepCopy() *MQTTImageSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTImageStatus) DeepCopyInto(out *MQTTImageStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTImageStatus.
func (in *MQTTImageStatus) DeepCopy() *MQTTImageStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLawnMower) DeepCopyInto(out *MQTTLawnMower) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLawnMower.
func (in *MQTTLawnMower) DeepCopy() *MQTTLawnMower {
	if in == nil {
		return nil
	}
	out := new(MQTTLawnMower)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTLawnMower) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLawnMowerList) DeepCopyInto(out *MQTTLawnMowerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTLawnMower, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLawnMowerList.
func (in *MQTTLawnMowerList) DeepCopy() *MQTTLawnMowerList {
	if in == nil {
		return nil
	}
	out := new(MQTTLawnMowerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTLawnMowerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLawnMowerSpec) DeepCopyInto(out *MQTTLawnMowerSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLawnMowerSpec.
func (in *MQTTLawnMowerSpec) DeepCopy() *MQTTLawnMowerSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTLawnMowerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLawnMowerStatus) DeepCopyInto(out *MQTTLawnMowerStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLawnMowerStatus.
func (in *MQTTLawnMowerStatus) DeepCopy() *MQTTLawnMowerStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTLawnMowerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLight) DeepCopyInto(out *MQTTLight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLight.
func (in *MQTTLight) DeepCopy() *MQTTLight {
	if in == nil {
		return nil
	}
	out := new(MQTTLight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTLight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLightList) DeepCopyInto(out *MQTTLightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTLight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLightList.
func (in *MQTTLightList) DeepCopy() *MQTTLightList {
	if in == nil {
		return nil
	}
	out := new(MQTTLightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTLightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLightSpec) DeepCopyInto(out *MQTTLightSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.BrightnessScale != nil {
		in, out := &in.BrightnessScale, &out.BrightnessScale
		*out = new(int)
		**out = **in
	}
	if in.EffectList != nil {
		in, out := &in.EffectList, &out.EffectList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinMireds != nil {
		in, out := &in.MinMireds, &out.MinMireds
		*out = new(int)
		**out = **in
	}
	if in.MaxMireds != nil {
		in, out := &in.MaxMireds, &out.MaxMireds
		*out = new(int)
		**out = **in
	}
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
	if in.Brightness != nil {
		in, out := &in.Brightness, &out.Brightness
		*out = new(bool)
		**out = **in
	}
	if in.ColorTemp != nil {
		in, out := &in.ColorTemp, &out.ColorTemp
		*out = new(bool)
		**out = **in
	}
	if in.Effect != nil {
		in, out := &in.Effect, &out.Effect
		*out = new(bool)
		**out = **in
	}
	if in.SupportedColorModes != nil {
		in, out := &in.SupportedColorModes, &out.SupportedColorModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLightSpec.
func (in *MQTTLightSpec) DeepCopy() *MQTTLightSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTLightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLightStatus) DeepCopyInto(out *MQTTLightStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLightStatus.
func (in *MQTTLightStatus) DeepCopy() *MQTTLightStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTLightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLock) DeepCopyInto(out *MQTTLock) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLock.
func (in *MQTTLock) DeepCopy() *MQTTLock {
	if in == nil {
		return nil
	}
	out := new(MQTTLock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTLock) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLockList) DeepCopyInto(out *MQTTLockList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTLock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLockList.
func (in *MQTTLockList) DeepCopy() *MQTTLockList {
	if in == nil {
		return nil
	}
	out := new(MQTTLockList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTLockList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLockSpec) DeepCopyInto(out *MQTTLockSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLockSpec.
func (in *MQTTLockSpec) DeepCopy() *MQTTLockSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTLockSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTLockStatus) DeepCopyInto(out *MQTTLockStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTLockStatus.
func (in *MQTTLockStatus) DeepCopy() *MQTTLockStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTLockStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTNotify) DeepCopyInto(out *MQTTNotify) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTNotify.
func (in *MQTTNotify) DeepCopy() *MQTTNotify {
	if in == nil {
		return nil
	}
	out := new(MQTTNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTNotify) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTNotifyList) DeepCopyInto(out *MQTTNotifyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTNotify, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTNotifyList.
func (in *MQTTNotifyList) DeepCopy() *MQTTNotifyList {
	if in == nil {
		return nil
	}
	out := new(MQTTNotifyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTNotifyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTNotifySpec) DeepCopyInto(out *MQTTNotifySpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTNotifySpec.
func (in *MQTTNotifySpec) DeepCopy() *MQTTNotifySpec {
	if in == nil {
		return nil
	}
	out := new(MQTTNotifySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTNotifyStatus) DeepCopyInto(out *MQTTNotifyStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTNotifyStatus.
func (in *MQTTNotifyStatus) DeepCopy() *MQTTNotifyStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTNotifyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTNumber) DeepCopyInto(out *MQTTNumber) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTNumber.
func (in *MQTTNumber) DeepCopy() *MQTTNumber {
	if in == nil {
		return nil
	}
	out := new(MQTTNumber)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTNumber) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTNumberList) DeepCopyInto(out *MQTTNumberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTNumber, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTNumberList.
func (in *MQTTNumberList) DeepCopy() *MQTTNumberList {
	if in == nil {
		return nil
	}
	out := new(MQTTNumberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTNumberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTNumberSpec) DeepCopyInto(out *MQTTNumberSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Step != nil {
		in, out := &in.Step, &out.Step
		*out = new(float64)
		**out = **in
	}
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTNumberSpec.
func (in *MQTTNumberSpec) DeepCopy() *MQTTNumberSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTNumberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTNumberStatus) DeepCopyInto(out *MQTTNumberStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTNumberStatus.
func (in *MQTTNumberStatus) DeepCopy() *MQTTNumberStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTNumberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTScene) DeepCopyInto(out *MQTTScene) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTScene.
func (in *MQTTScene) DeepCopy() *MQTTScene {
	if in == nil {
		return nil
	}
	out := new(MQTTScene)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTScene) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSceneList) DeepCopyInto(out *MQTTSceneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTScene, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSceneList.
func (in *MQTTSceneList) DeepCopy() *MQTTSceneList {
	if in == nil {
		return nil
	}
	out := new(MQTTSceneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTSceneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSceneSpec) DeepCopyInto(out *MQTTSceneSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSceneSpec.
func (in *MQTTSceneSpec) DeepCopy() *MQTTSceneSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTSceneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSceneStatus) DeepCopyInto(out *MQTTSceneStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSceneStatus.
func (in *MQTTSceneStatus) DeepCopy() *MQTTSceneStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTSceneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSelect) DeepCopyInto(out *MQTTSelect) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSelect.
func (in *MQTTSelect) DeepCopy() *MQTTSelect {
	if in == nil {
		return nil
	}
	out := new(MQTTSelect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTSelect) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSelectList) DeepCopyInto(out *MQTTSelectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTSelect, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSelectList.
func (in *MQTTSelectList) DeepCopy() *MQTTSelectList {
	if in == nil {
		return nil
	}
	out := new(MQTTSelectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTSelectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSelectSpec) DeepCopyInto(out *MQTTSelectSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSelectSpec.
func (in *MQTTSelectSpec) DeepCopy() *MQTTSelectSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTSelectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSelectStatus) DeepCopyInto(out *MQTTSelectStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSelectStatus.
func (in *MQTTSelectStatus) DeepCopy() *MQTTSelectStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTSelectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSensor) DeepCopyInto(out *MQTTSensor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSensor.
func (in *MQTTSensor) DeepCopy() *MQTTSensor {
	if in == nil {
		return nil
	}
	out := new(MQTTSensor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTSensor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSensorList) DeepCopyInto(out *MQTTSensorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTSensor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSensorList.
func (in *MQTTSensorList) DeepCopy() *MQTTSensorList {
	if in == nil {
		return nil
	}
	out := new(MQTTSensorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTSensorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSensorSpec) DeepCopyInto(out *MQTTSensorSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.ExpireAfter != nil {
		in, out := &in.ExpireAfter, &out.ExpireAfter
		*out = new(int)
		**out = **in
	}
	if in.ForceUpdate != nil {
		in, out := &in.ForceUpdate, &out.ForceUpdate
		*out = new(bool)
		**out = **in
	}
	if in.SuggestedDisplayPrecision != nil {
		in, out := &in.SuggestedDisplayPrecision, &out.SuggestedDisplayPrecision
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSensorSpec.
func (in *MQTTSensorSpec) DeepCopy() *MQTTSensorSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTSensorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSensorStatus) DeepCopyInto(out *MQTTSensorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSensorStatus.
func (in *MQTTSensorStatus) DeepCopy() *MQTTSensorStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTSensorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSiren) DeepCopyInto(out *MQTTSiren) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSiren.
func (in *MQTTSiren) DeepCopy() *MQTTSiren {
	if in == nil {
		return nil
	}
	out := new(MQTTSiren)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTSiren) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSirenList) DeepCopyInto(out *MQTTSirenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTSiren, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSirenList.
func (in *MQTTSirenList) DeepCopy() *MQTTSirenList {
	if in == nil {
		return nil
	}
	out := new(MQTTSirenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTSirenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSirenSpec) DeepCopyInto(out *MQTTSirenSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.AvailableTones != nil {
		in, out := &in.AvailableTones, &out.AvailableTones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SupportTurnOn != nil {
		in, out := &in.SupportTurnOn, &out.SupportTurnOn
		*out = new(bool)
		**out = **in
	}
	if in.SupportTurnOff != nil {
		in, out := &in.SupportTurnOff, &out.SupportTurnOff
		*out = new(bool)
		**out = **in
	}
	if in.SupportDuration != nil {
		in, out := &in.SupportDuration, &out.SupportDuration
		*out = new(bool)
		**out = **in
	}
	if in.SupportVolumeSet != nil {
		in, out := &in.SupportVolumeSet, &out.SupportVolumeSet
		*out = new(bool)
		**out = **in
	}
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSirenSpec.
func (in *MQTTSirenSpec) DeepCopy() *MQTTSirenSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTSirenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSirenStatus) DeepCopyInto(out *MQTTSirenStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSirenStatus.
func (in *MQTTSirenStatus) DeepCopy() *MQTTSirenStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTSirenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSwitch) DeepCopyInto(out *MQTTSwitch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSwitch.
func (in *MQTTSwitch) DeepCopy() *MQTTSwitch {
	if in == nil {
		return nil
	}
	out := new(MQTTSwitch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTSwitch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSwitchList) DeepCopyInto(out *MQTTSwitchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTSwitch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSwitchList.
func (in *MQTTSwitchList) DeepCopy() *MQTTSwitchList {
	if in == nil {
		return nil
	}
	out := new(MQTTSwitchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTSwitchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSwitchSpec) DeepCopyInto(out *MQTTSwitchSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSwitchSpec.
func (in *MQTTSwitchSpec) DeepCopy() *MQTTSwitchSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTSwitchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSwitchStatus) DeepCopyInto(out *MQTTSwitchStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSwitchStatus.
func (in *MQTTSwitchStatus) DeepCopy() *MQTTSwitchStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTSwitchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTTag) DeepCopyInto(out *MQTTTag) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTTag.
func (in *MQTTTag) DeepCopy() *MQTTTag {
	if in == nil {
		return nil
	}
	out := new(MQTTTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTTag) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTTagList) DeepCopyInto(out *MQTTTagList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTTag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTTagList.
func (in *MQTTTagList) DeepCopy() *MQTTTagList {
	if in == nil {
		return nil
	}
	out := new(MQTTTagList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTTagList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTTagSpec) DeepCopyInto(out *MQTTTagSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTTagSpec.
func (in *MQTTTagSpec) DeepCopy() *MQTTTagSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTTagSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTTagStatus) DeepCopyInto(out *MQTTTagStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTTagStatus.
func (in *MQTTTagStatus) DeepCopy() *MQTTTagStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTTagStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTText) DeepCopyInto(out *MQTTText) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTText.
func (in *MQTTText) DeepCopy() *MQTTText {
	if in == nil {
		return nil
	}
	out := new(MQTTText)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTText) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTTextList) DeepCopyInto(out *MQTTTextList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTText, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTTextList.
func (in *MQTTTextList) DeepCopy() *MQTTTextList {
	if in == nil {
		return nil
	}
	out := new(MQTTTextList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTTextList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTTextSpec) DeepCopyInto(out *MQTTTextSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTTextSpec.
func (in *MQTTTextSpec) DeepCopy() *MQTTTextSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTTextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTTextStatus) DeepCopyInto(out *MQTTTextStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTTextStatus.
func (in *MQTTTextStatus) DeepCopy() *MQTTTextStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTTextStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTUpdate) DeepCopyInto(out *MQTTUpdate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTUpdate.
func (in *MQTTUpdate) DeepCopy() *MQTTUpdate {
	if in == nil {
		return nil
	}
	out := new(MQTTUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTUpdate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTUpdateList) DeepCopyInto(out *MQTTUpdateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTUpdate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTUpdateList.
func (in *MQTTUpdateList) DeepCopy() *MQTTUpdateList {
	if in == nil {
		return nil
	}
	out := new(MQTTUpdateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTUpdateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTUpdateSpec) DeepCopyInto(out *MQTTUpdateSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTUpdateSpec.
func (in *MQTTUpdateSpec) DeepCopy() *MQTTUpdateSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTUpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTUpdateStatus) DeepCopyInto(out *MQTTUpdateStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTUpdateStatus.
func (in *MQTTUpdateStatus) DeepCopy() *MQTTUpdateStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTUpdateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTVacuum) DeepCopyInto(out *MQTTVacuum) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTVacuum.
func (in *MQTTVacuum) DeepCopy() *MQTTVacuum {
	if in == nil {
		return nil
	}
	out := new(MQTTVacuum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTVacuum) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTVacuumList) DeepCopyInto(out *MQTTVacuumList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTVacuum, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTVacuumList.
func (in *MQTTVacuumList) DeepCopy() *MQTTVacuumList {
	if in == nil {
		return nil
	}
	out := new(MQTTVacuumList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTVacuumList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTVacuumSpec) DeepCopyInto(out *MQTTVacuumSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.FanSpeedList != nil {
		in, out := &in.FanSpeedList, &out.FanSpeedList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SupportedFeatures != nil {
		in, out := &in.SupportedFeatures, &out.SupportedFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTVacuumSpec.
func (in *MQTTVacuumSpec) DeepCopy() *MQTTVacuumSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTVacuumSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTVacuumStatus) DeepCopyInto(out *MQTTVacuumStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTVacuumStatus.
func (in *MQTTVacuumStatus) DeepCopy() *MQTTVacuumStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTVacuumStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTValve) DeepCopyInto(out *MQTTValve) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTValve.
func (in *MQTTValve) DeepCopy() *MQTTValve {
	if in == nil {
		return nil
	}
	out := new(MQTTValve)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTValve) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTValveList) DeepCopyInto(out *MQTTValveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTValve, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTValveList.
func (in *MQTTValveList) DeepCopy() *MQTTValveList {
	if in == nil {
		return nil
	}
	out := new(MQTTValveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTValveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTValveSpec) DeepCopyInto(out *MQTTValveSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.ReportsPosition != nil {
		in, out := &in.ReportsPosition, &out.ReportsPosition
		*out = new(bool)
		**out = **in
	}
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTValveSpec.
func (in *MQTTValveSpec) DeepCopy() *MQTTValveSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTValveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTValveStatus) DeepCopyInto(out *MQTTValveStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTValveStatus.
func (in *MQTTValveStatus) DeepCopy() *MQTTValveStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTValveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTWaterHeater) DeepCopyInto(out *MQTTWaterHeater) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTWaterHeater.
func (in *MQTTWaterHeater) DeepCopy() *MQTTWaterHeater {
	if in == nil {
		return nil
	}
	out := new(MQTTWaterHeater)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTWaterHeater) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTWaterHeaterList) DeepCopyInto(out *MQTTWaterHeaterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTWaterHeater, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTWaterHeaterList.
func (in *MQTTWaterHeaterList) DeepCopy() *MQTTWaterHeaterList {
	if in == nil {
		return nil
	}
	out := new(MQTTWaterHeaterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MQTTWaterHeaterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTWaterHeaterSpec) DeepCopyInto(out *MQTTWaterHeaterSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.Modes != nil {
		in, out := &in.Modes, &out.Modes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinTemp != nil {
		in, out := &in.MinTemp, &out.MinTemp
		*out = new(float64)
		**out = **in
	}
	if in.MaxTemp != nil {
		in, out := &in.MaxTemp, &out.MaxTemp
		*out = new(float64)
		**out = **in
	}
	if in.Precision != nil {
		in, out := &in.Precision, &out.Precision
		*out = new(float64)
		**out = **in
	}
	if in.Optimistic != nil {
		in, out := &in.Optimistic, &out.Optimistic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTWaterHeaterSpec.
func (in *MQTTWaterHeaterSpec) DeepCopy() *MQTTWaterHeaterSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTWaterHeaterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTWaterHeaterStatus) DeepCopyInto(out *MQTTWaterHeaterStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTWaterHeaterStatus.
func (in *MQTTWaterHeaterStatus) DeepCopy() *MQTTWaterHeaterStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTWaterHeaterStatus)
	in.DeepCopyInto(out)
	return out
}
